[package]
name = "expr-builtin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bash-builtins = "0.4.1"
mexprp = "0.3.1"

[lib]
crate-type = [ "cdylib" ]
